# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import elastic_pb2 as elastic__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in elastic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ElasticSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMatch = channel.unary_unary(
                '/elastic.ElasticSearch/GetMatch',
                request_serializer=elastic__pb2.GetMatchRequest.SerializeToString,
                response_deserializer=elastic__pb2.GetMatchResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/elastic.ElasticSearch/UpdateUser',
                request_serializer=elastic__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=elastic__pb2.UpdateUserResponse.FromString,
                _registered_method=True)


class ElasticSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElasticSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatch,
                    request_deserializer=elastic__pb2.GetMatchRequest.FromString,
                    response_serializer=elastic__pb2.GetMatchResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=elastic__pb2.UpdateUserRequest.FromString,
                    response_serializer=elastic__pb2.UpdateUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elastic.ElasticSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('elastic.ElasticSearch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ElasticSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elastic.ElasticSearch/GetMatch',
            elastic__pb2.GetMatchRequest.SerializeToString,
            elastic__pb2.GetMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elastic.ElasticSearch/UpdateUser',
            elastic__pb2.UpdateUserRequest.SerializeToString,
            elastic__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
