# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: elastic.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'elastic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\relastic.proto\x12\x07\x65lastic\"~\n\x0fGetMatchRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x0f\n\x07\x61ge_min\x18\x04 \x01(\x05\x12\x0f\n\x07\x61ge_max\x18\x05 \x01(\x05\x12\x10\n\x08\x64istance\x18\x06 \x01(\x05\x12\r\n\x05limit\x18\x07 \x01(\x05\"3\n\x10GetMatchResponse\x12\x10\n\x08user_ids\x18\x01 \x03(\t\x12\r\n\x05total\x18\x02 \x01(\x05\"[\n\x11UpdateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0b\n\x03lon\x18\x03 \x01(\x02\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0e\n\x06gender\x18\x05 \x01(\t\"6\n\x12UpdateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x08\x32\x9b\x01\n\rElasticSearch\x12\x41\n\x08GetMatch\x12\x18.elastic.GetMatchRequest\x1a\x19.elastic.GetMatchResponse\"\x00\x12G\n\nUpdateUser\x12\x1a.elastic.UpdateUserRequest\x1a\x1b.elastic.UpdateUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elastic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMATCHREQUEST']._serialized_start=26
  _globals['_GETMATCHREQUEST']._serialized_end=152
  _globals['_GETMATCHRESPONSE']._serialized_start=154
  _globals['_GETMATCHRESPONSE']._serialized_end=205
  _globals['_UPDATEUSERREQUEST']._serialized_start=207
  _globals['_UPDATEUSERREQUEST']._serialized_end=298
  _globals['_UPDATEUSERRESPONSE']._serialized_start=300
  _globals['_UPDATEUSERRESPONSE']._serialized_end=354
  _globals['_ELASTICSEARCH']._serialized_start=357
  _globals['_ELASTICSEARCH']._serialized_end=512
# @@protoc_insertion_point(module_scope)
