# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accounts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'accounts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63\x63ounts.proto\x12\x17\x64\x61ting.service.accounts\"<\n\nGetRequest\x12\x13\n\x0btelegram_id\x18\x01 \x01(\x03\x12\x19\n\x11telegram_username\x18\x02 \x01(\t\"q\n\x0bGetResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0btelegram_id\x18\x02 \x01(\x03\x12\x19\n\x11telegram_username\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t2c\n\x0f\x41\x63\x63ountsService\x12P\n\x03Get\x12#.dating.service.accounts.GetRequest\x1a$.dating.service.accounts.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accounts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=43
  _globals['_GETREQUEST']._serialized_end=103
  _globals['_GETRESPONSE']._serialized_start=105
  _globals['_GETRESPONSE']._serialized_end=218
  _globals['_ACCOUNTSSERVICE']._serialized_start=220
  _globals['_ACCOUNTSSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
