version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s
    restart: always

  elastic-service:
    build:
      context: ./elastic
      dockerfile: Dockerfile
    container_name: elastic-service
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "50051:50051"
    networks:
      - elastic
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always

volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic:
    driver: bridge
