version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./resources/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./resources/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

  clickhouse_service:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS: "1"
      CLICKHOUSE_INIT_TIMEOUT: 300
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "default"
    volumes:
      - ./resources/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./resources/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --query \"SELECT 1\" --user default --password default || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  clickhouse:
    build:
      context: ./clickhouse
      dockerfile: Dockerfile
    container_name: clickhouse
    depends_on:
      rabbitmq:
        condition: service_healthy
      clickhouse_service:
        condition: service_healthy
    ports:
      - "127.0.0.1:5069:5069"
