services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 10s
      retries: 3
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - external_network

  accounts_db:
    image: 'postgres:15.5'
    container_name: accounts_db
    environment:
      - POSTGRES_DB=${ACCOUNTS_DB_NAME}
      - POSTGRES_USER=${ACCOUNTS_DB_USER}
      - POSTGRES_PASSWORD=${ACCOUNTS_DB_PASS}
    restart: unless-stopped
    ports:
      - 127.0.0.1:5442:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "test", "-U", "${ACCOUNTS_DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - accounts_pgdata:/var/lib/postgresql/data
    networks:
      - accounts_network

  accounts_service:
    build: ./accounts_service
    container_name: accounts_service
    command: ash -c "poetry run yoyo apply -b && poetry run python -m src"
    stop_signal: SIGINT
    restart: unless-stopped
    depends_on:
      accounts_db:
        condition: service_healthy
    env_file:
      - accounts_service/config/.env
    volumes:
      - ./accounts_service:/usr/src/dating/accounts_service
    ports:
      - 8001:8001
      - 8010:1337
    networks:
      - accounts_network
      - external_network

  bot_service:
    build: ./bot_service
    container_name: bot_service
    command: ash -c "poetry run python -m src"
    stop_signal: SIGINT
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - bot_service/config/.env
    volumes:
      - ./bot_service:/usr/src/dating/bot_service
    networks:
      - bot_network
      - external_network

networks:
  accounts_network:
    driver: bridge
  bot_network:
    driver: bridge
  external_network:
    driver: bridge

volumes:
  accounts_pgdata:
  rabbitmq_data: