services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 3s
      timeout: 10s
      retries: 3
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - external_network

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    volumes:
      - ./resources/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./resources/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - clickhouse_data:/var/lib/clickhouse
    networks:
      - external_network

networks:
  external_network:
    driver: bridge

volumes:
  rabbitmq_data:
  clickhouse_data:
