# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profiles.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'profiles.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprofiles.proto\x12\x17\x64\x61ting.service.profiles\"%\n\x12ProfilesGetRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\xc3\x01\n\x13ProfilesGetResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12/\n\x06gender\x18\x06 \x01(\x0e\x32\x1f.dating.service.profiles.Gender\x12\x11\n\tbiography\x18\x07 \x01(\t\x12\x17\n\x0f\x61\x64\x64itional_info\x18\x08 \x01(\t*,\n\x06Gender\x12\x0f\n\x0bGENDER_MALE\x10\x00\x12\x11\n\rGENDER_FEMALE\x10\x01\x32s\n\x0fProfilesService\x12`\n\x03Get\x12+.dating.service.profiles.ProfilesGetRequest\x1a,.dating.service.profiles.ProfilesGetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profiles_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENDER']._serialized_start=280
  _globals['_GENDER']._serialized_end=324
  _globals['_PROFILESGETREQUEST']._serialized_start=43
  _globals['_PROFILESGETREQUEST']._serialized_end=80
  _globals['_PROFILESGETRESPONSE']._serialized_start=83
  _globals['_PROFILESGETRESPONSE']._serialized_end=278
  _globals['_PROFILESSERVICE']._serialized_start=326
  _globals['_PROFILESSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
