# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import profiles_pb2 as profiles__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in profiles_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfilesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/dating.service.profiles.ProfilesService/Create',
                request_serializer=profiles__pb2.ProfileCreateRequest.SerializeToString,
                response_deserializer=profiles__pb2.ProfileCreateResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/dating.service.profiles.ProfilesService/Get',
                request_serializer=profiles__pb2.ProfilesGetRequest.SerializeToString,
                response_deserializer=profiles__pb2.ProfilesGetResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/dating.service.profiles.ProfilesService/Update',
                request_serializer=profiles__pb2.ProfileUpdateRequest.SerializeToString,
                response_deserializer=profiles__pb2.ProfilesUpdateResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/dating.service.profiles.ProfilesService/Delete',
                request_serializer=profiles__pb2.ProfileDeleteRequest.SerializeToString,
                response_deserializer=profiles__pb2.ProfilesDeleteResponse.FromString,
                _registered_method=True)


class ProfilesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfilesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=profiles__pb2.ProfileCreateRequest.FromString,
                    response_serializer=profiles__pb2.ProfileCreateResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=profiles__pb2.ProfilesGetRequest.FromString,
                    response_serializer=profiles__pb2.ProfilesGetResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=profiles__pb2.ProfileUpdateRequest.FromString,
                    response_serializer=profiles__pb2.ProfilesUpdateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=profiles__pb2.ProfileDeleteRequest.FromString,
                    response_serializer=profiles__pb2.ProfilesDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dating.service.profiles.ProfilesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dating.service.profiles.ProfilesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfilesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/dating.service.profiles.ProfilesService/Create',
            profiles__pb2.ProfileCreateRequest.SerializeToString,
            profiles__pb2.ProfileCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/dating.service.profiles.ProfilesService/Get',
            profiles__pb2.ProfilesGetRequest.SerializeToString,
            profiles__pb2.ProfilesGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/dating.service.profiles.ProfilesService/Update',
            profiles__pb2.ProfileUpdateRequest.SerializeToString,
            profiles__pb2.ProfilesUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/dating.service.profiles.ProfilesService/Delete',
            profiles__pb2.ProfileDeleteRequest.SerializeToString,
            profiles__pb2.ProfilesDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
