# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import recommendations_pb2 as recommendations__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommendations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMatches = channel.unary_unary(
                '/dating.service.recommendations.RecommendationsService/GetMatches',
                request_serializer=recommendations__pb2.RecommendationsGetMatchRequest.SerializeToString,
                response_deserializer=recommendations__pb2.RecommendationsGetMatchResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/dating.service.recommendations.RecommendationsService/UpdateUser',
                request_serializer=recommendations__pb2.RecommendationsUpdateUserRequest.SerializeToString,
                response_deserializer=recommendations__pb2.RecommendationsUpdateUserResponse.FromString,
                _registered_method=True)


class RecommendationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMatches': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatches,
                    request_deserializer=recommendations__pb2.RecommendationsGetMatchRequest.FromString,
                    response_serializer=recommendations__pb2.RecommendationsGetMatchResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=recommendations__pb2.RecommendationsUpdateUserRequest.FromString,
                    response_serializer=recommendations__pb2.RecommendationsUpdateUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dating.service.recommendations.RecommendationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dating.service.recommendations.RecommendationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dating.service.recommendations.RecommendationsService/GetMatches',
            recommendations__pb2.RecommendationsGetMatchRequest.SerializeToString,
            recommendations__pb2.RecommendationsGetMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dating.service.recommendations.RecommendationsService/UpdateUser',
            recommendations__pb2.RecommendationsUpdateUserRequest.SerializeToString,
            recommendations__pb2.RecommendationsUpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
