# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import recommendations_pb2 as recommendations__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommendations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateProfile = channel.unary_unary(
                '/dating.service.recommendations.RecommendationsService/UpdateProfile',
                request_serializer=recommendations__pb2.RecommendationsUpdateProfileRequest.SerializeToString,
                response_deserializer=recommendations__pb2.RecommendationsUpdateProfileResponse.FromString,
                _registered_method=True)
        self.SearchProfiles = channel.unary_unary(
                '/dating.service.recommendations.RecommendationsService/SearchProfiles',
                request_serializer=recommendations__pb2.RecommendationsSearchProfilesRequest.SerializeToString,
                response_deserializer=recommendations__pb2.RecommendationsSearchProfilesResponse.FromString,
                _registered_method=True)
        self.UpdateCity = channel.unary_unary(
                '/dating.service.recommendations.RecommendationsService/UpdateCity',
                request_serializer=recommendations__pb2.RecommendationsUpdateCityRequest.SerializeToString,
                response_deserializer=recommendations__pb2.RecommendationsUpdateCityResponse.FromString,
                _registered_method=True)
        self.SearchCities = channel.unary_unary(
                '/dating.service.recommendations.RecommendationsService/SearchCities',
                request_serializer=recommendations__pb2.RecommendationsSearchCitiesRequest.SerializeToString,
                response_deserializer=recommendations__pb2.RecommendationsSearchCitiesResponse.FromString,
                _registered_method=True)


class RecommendationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchCities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=recommendations__pb2.RecommendationsUpdateProfileRequest.FromString,
                    response_serializer=recommendations__pb2.RecommendationsUpdateProfileResponse.SerializeToString,
            ),
            'SearchProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProfiles,
                    request_deserializer=recommendations__pb2.RecommendationsSearchProfilesRequest.FromString,
                    response_serializer=recommendations__pb2.RecommendationsSearchProfilesResponse.SerializeToString,
            ),
            'UpdateCity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCity,
                    request_deserializer=recommendations__pb2.RecommendationsUpdateCityRequest.FromString,
                    response_serializer=recommendations__pb2.RecommendationsUpdateCityResponse.SerializeToString,
            ),
            'SearchCities': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCities,
                    request_deserializer=recommendations__pb2.RecommendationsSearchCitiesRequest.FromString,
                    response_serializer=recommendations__pb2.RecommendationsSearchCitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dating.service.recommendations.RecommendationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dating.service.recommendations.RecommendationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/dating.service.recommendations.RecommendationsService/UpdateProfile',
            recommendations__pb2.RecommendationsUpdateProfileRequest.SerializeToString,
            recommendations__pb2.RecommendationsUpdateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/dating.service.recommendations.RecommendationsService/SearchProfiles',
            recommendations__pb2.RecommendationsSearchProfilesRequest.SerializeToString,
            recommendations__pb2.RecommendationsSearchProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dating.service.recommendations.RecommendationsService/UpdateCity',
            recommendations__pb2.RecommendationsUpdateCityRequest.SerializeToString,
            recommendations__pb2.RecommendationsUpdateCityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchCities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dating.service.recommendations.RecommendationsService/SearchCities',
            recommendations__pb2.RecommendationsSearchCitiesRequest.SerializeToString,
            recommendations__pb2.RecommendationsSearchCitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
