# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendations.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'recommendations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..profiles import profiles_pb2 as profiles__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x1e\x64\x61ting.service.recommendations\x1a\x0eprofiles.proto\"\xae\x01\n\x1eRecommendationsGetMatchRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12/\n\x06gender\x18\x03 \x01(\x0e\x32\x1f.dating.service.profiles.Gender\x12\x0f\n\x07\x61ge_min\x18\x04 \x01(\x05\x12\x0f\n\x07\x61ge_max\x18\x05 \x01(\x05\x12\x10\n\x08\x64istance\x18\x06 \x01(\x05\x12\r\n\x05limit\x18\x07 \x01(\x05\"B\n\x1fRecommendationsGetMatchResponse\x12\x10\n\x08user_ids\x18\x01 \x03(\t\x12\r\n\x05total\x18\x02 \x01(\x05\"j\n RecommendationsUpdateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0b\n\x03lon\x18\x03 \x01(\x02\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0e\n\x06gender\x18\x05 \x01(\t\"E\n!RecommendationsUpdateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x08\x32\xbc\x02\n\x16RecommendationsService\x12\x8d\x01\n\nGetMatches\x12>.dating.service.recommendations.RecommendationsGetMatchRequest\x1a?.dating.service.recommendations.RecommendationsGetMatchResponse\x12\x91\x01\n\nUpdateUser\x12@.dating.service.recommendations.RecommendationsUpdateUserRequest\x1a\x41.dating.service.recommendations.RecommendationsUpdateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONSGETMATCHREQUEST']._serialized_start=74
  _globals['_RECOMMENDATIONSGETMATCHREQUEST']._serialized_end=248
  _globals['_RECOMMENDATIONSGETMATCHRESPONSE']._serialized_start=250
  _globals['_RECOMMENDATIONSGETMATCHRESPONSE']._serialized_end=316
  _globals['_RECOMMENDATIONSUPDATEUSERREQUEST']._serialized_start=318
  _globals['_RECOMMENDATIONSUPDATEUSERREQUEST']._serialized_end=424
  _globals['_RECOMMENDATIONSUPDATEUSERRESPONSE']._serialized_start=426
  _globals['_RECOMMENDATIONSUPDATEUSERRESPONSE']._serialized_end=495
  _globals['_RECOMMENDATIONSSERVICE']._serialized_start=498
  _globals['_RECOMMENDATIONSSERVICE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
