# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import clickhouse_pb2 as clickhouse__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in clickhouse_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClickHouseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserInteractions = channel.unary_unary(
                '/clickhouse.ClickHouseService/GetUserInteractions',
                request_serializer=clickhouse__pb2.GetUserInteractionsRequest.SerializeToString,
                response_deserializer=clickhouse__pb2.GetUserInteractionsResponse.FromString,
                _registered_method=True)
        self.GetUserReceivedLikes = channel.unary_unary(
                '/clickhouse.ClickHouseService/GetUserReceivedLikes',
                request_serializer=clickhouse__pb2.GetUserReceivedLikesRequest.SerializeToString,
                response_deserializer=clickhouse__pb2.GetUserReceivedLikesResponse.FromString,
                _registered_method=True)
        self.GetUserReceivedDislikes = channel.unary_unary(
                '/clickhouse.ClickHouseService/GetUserReceivedDislikes',
                request_serializer=clickhouse__pb2.GetUserReceivedDislikesRequest.SerializeToString,
                response_deserializer=clickhouse__pb2.GetUserReceivedDislikesResponse.FromString,
                _registered_method=True)
        self.GetUserMutualLikes = channel.unary_unary(
                '/clickhouse.ClickHouseService/GetUserMutualLikes',
                request_serializer=clickhouse__pb2.GetUserMutualLikesRequest.SerializeToString,
                response_deserializer=clickhouse__pb2.GetUserMutualLikesResponse.FromString,
                _registered_method=True)


class ClickHouseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserInteractions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserReceivedLikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserReceivedDislikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserMutualLikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClickHouseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserInteractions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserInteractions,
                    request_deserializer=clickhouse__pb2.GetUserInteractionsRequest.FromString,
                    response_serializer=clickhouse__pb2.GetUserInteractionsResponse.SerializeToString,
            ),
            'GetUserReceivedLikes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserReceivedLikes,
                    request_deserializer=clickhouse__pb2.GetUserReceivedLikesRequest.FromString,
                    response_serializer=clickhouse__pb2.GetUserReceivedLikesResponse.SerializeToString,
            ),
            'GetUserReceivedDislikes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserReceivedDislikes,
                    request_deserializer=clickhouse__pb2.GetUserReceivedDislikesRequest.FromString,
                    response_serializer=clickhouse__pb2.GetUserReceivedDislikesResponse.SerializeToString,
            ),
            'GetUserMutualLikes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserMutualLikes,
                    request_deserializer=clickhouse__pb2.GetUserMutualLikesRequest.FromString,
                    response_serializer=clickhouse__pb2.GetUserMutualLikesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clickhouse.ClickHouseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clickhouse.ClickHouseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClickHouseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserInteractions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clickhouse.ClickHouseService/GetUserInteractions',
            clickhouse__pb2.GetUserInteractionsRequest.SerializeToString,
            clickhouse__pb2.GetUserInteractionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserReceivedLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clickhouse.ClickHouseService/GetUserReceivedLikes',
            clickhouse__pb2.GetUserReceivedLikesRequest.SerializeToString,
            clickhouse__pb2.GetUserReceivedLikesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserReceivedDislikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clickhouse.ClickHouseService/GetUserReceivedDislikes',
            clickhouse__pb2.GetUserReceivedDislikesRequest.SerializeToString,
            clickhouse__pb2.GetUserReceivedDislikesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserMutualLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clickhouse.ClickHouseService/GetUserMutualLikes',
            clickhouse__pb2.GetUserMutualLikesRequest.SerializeToString,
            clickhouse__pb2.GetUserMutualLikesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
