# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clickhouse.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'clickhouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lickhouse.proto\x12\nclickhouse\"-\n\x1aGetUserInteractionsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"L\n\x1bGetUserInteractionsResponse\x12-\n\x0cinteractions\x18\x01 \x03(\x0b\x32\x17.clickhouse.Interaction\".\n\x1bGetUserReceivedLikesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"?\n\x1cGetUserReceivedLikesResponse\x12\x1f\n\x05likes\x18\x01 \x03(\x0b\x32\x10.clickhouse.Like\"1\n\x1eGetUserReceivedDislikesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"H\n\x1fGetUserReceivedDislikesResponse\x12%\n\x08\x64islikes\x18\x01 \x03(\x0b\x32\x13.clickhouse.Dislike\"^\n\x0bInteraction\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x10\n\x08liker_id\x18\x02 \x01(\t\x12\x10\n\x08liked_id\x18\x03 \x01(\t\x12\x18\n\x10interaction_type\x18\x04 \x01(\t\"=\n\x04Like\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x10\n\x08liker_id\x18\x02 \x01(\t\x12\x10\n\x08liked_id\x18\x03 \x01(\t\"F\n\x07\x44islike\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x13\n\x0b\x64isliker_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64isliked_id\x18\x03 \x01(\t\",\n\x19GetUserMutualLikesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"=\n\nMutualLike\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05user1\x18\x02 \x01(\t\x12\r\n\x05user2\x18\x03 \x01(\t\"J\n\x1aGetUserMutualLikesResponse\x12,\n\x0cmutual_likes\x18\x01 \x03(\x0b\x32\x16.clickhouse.MutualLike2\xbf\x03\n\x11\x43lickHouseService\x12\x66\n\x13GetUserInteractions\x12&.clickhouse.GetUserInteractionsRequest\x1a\'.clickhouse.GetUserInteractionsResponse\x12i\n\x14GetUserReceivedLikes\x12\'.clickhouse.GetUserReceivedLikesRequest\x1a(.clickhouse.GetUserReceivedLikesResponse\x12r\n\x17GetUserReceivedDislikes\x12*.clickhouse.GetUserReceivedDislikesRequest\x1a+.clickhouse.GetUserReceivedDislikesResponse\x12\x63\n\x12GetUserMutualLikes\x12%.clickhouse.GetUserMutualLikesRequest\x1a&.clickhouse.GetUserMutualLikesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clickhouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERINTERACTIONSREQUEST']._serialized_start=32
  _globals['_GETUSERINTERACTIONSREQUEST']._serialized_end=77
  _globals['_GETUSERINTERACTIONSRESPONSE']._serialized_start=79
  _globals['_GETUSERINTERACTIONSRESPONSE']._serialized_end=155
  _globals['_GETUSERRECEIVEDLIKESREQUEST']._serialized_start=157
  _globals['_GETUSERRECEIVEDLIKESREQUEST']._serialized_end=203
  _globals['_GETUSERRECEIVEDLIKESRESPONSE']._serialized_start=205
  _globals['_GETUSERRECEIVEDLIKESRESPONSE']._serialized_end=268
  _globals['_GETUSERRECEIVEDDISLIKESREQUEST']._serialized_start=270
  _globals['_GETUSERRECEIVEDDISLIKESREQUEST']._serialized_end=319
  _globals['_GETUSERRECEIVEDDISLIKESRESPONSE']._serialized_start=321
  _globals['_GETUSERRECEIVEDDISLIKESRESPONSE']._serialized_end=393
  _globals['_INTERACTION']._serialized_start=395
  _globals['_INTERACTION']._serialized_end=489
  _globals['_LIKE']._serialized_start=491
  _globals['_LIKE']._serialized_end=552
  _globals['_DISLIKE']._serialized_start=554
  _globals['_DISLIKE']._serialized_end=624
  _globals['_GETUSERMUTUALLIKESREQUEST']._serialized_start=626
  _globals['_GETUSERMUTUALLIKESREQUEST']._serialized_end=670
  _globals['_MUTUALLIKE']._serialized_start=672
  _globals['_MUTUALLIKE']._serialized_end=733
  _globals['_GETUSERMUTUALLIKESRESPONSE']._serialized_start=735
  _globals['_GETUSERMUTUALLIKESRESPONSE']._serialized_end=809
  _globals['_CLICKHOUSESERVICE']._serialized_start=812
  _globals['_CLICKHOUSESERVICE']._serialized_end=1259
# @@protoc_insertion_point(module_scope)
